# Site settings
title: Kaushik Raj
header-img: img/bg/home.jpg
email: kaushik.raj@gmail.com
description: "Personal website of Kaushik Raj"
baseurl: ""
url: "http://kaushikraj.com"
linkedin_username: kaushikraj
github_username:  kaushikraj

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "rakefile"]
